### ISSUE TITLE
Provide a pot file

### ISSUE THREAD

**Issue by sabriunal** [iman-salmani/iplan#13]
Hi, I tried but got some error getting a fully translatable pot file.

Could you provide a pot file to make it easy to translate IPlan?

**Comment by iman-salmani** [comment]
Hi, can you paste the errors or warnings here?
if you mean these warnings:
```
xgettext: warning: file 'src/application.rs' extension 'rs' is unknown; will try C
src/application.rs:38: warning: unterminated character constant
```
I'm aware of this it seems to by default ```xgettext``` don't have a parser for rust but it's okay. (added to list)

**Comment by iman-salmani** [comment]
fixed
