### ISSUE TITLE
Subtask titles seem empty

### ISSUE THREAD

**Issue by sabriunal** [iman-salmani/iplan#19]
Hi, I added three subtasks but their titles seem empty.

OS: Ubuntu 23.04
IPlan version: Source code: 3c79c776dbf8d4f39703d7634d9185fb30293e02

[Ekran Kaydı - 2023-06-03 10-12-33.webm](https://github.com/iman-salmani/iplan/assets/6218679/bc63cc9d-b4af-4d3d-b4f3-d400d4914318)

**Comment by iman-salmani** [comment]
Hi
Names are updated after their entries are activated by pressing Enter key. (you can cancel it by Escape key).
It seems should be more clear. for example by adding a activate key like the Project Edit window or updating it whenever the entry text changes.

**Comment by iman-salmani** [comment]
Hi @sabriunal 
Now Task updates in the database while editing name entry. still, you can cancel editing by pressing the Escape key.
