### ISSUE TITLE
[Feature Request] Make Esc cancel operations

### ISSUE THREAD

**Issue by hyuri** [iman-salmani/iplan#28]
Hi!

It would be nice if we were able to cancel renaming (of tasks, projects, etc.) and close the search and other dialogs by pressing the Esc key.

In the case of the search dialog, it makes it easier when we press Ctrl + F to press Esc to cancel/close the search dialog.

**Comment by iman-salmani** [comment]
I agree, for now, you can cancel renaming tasks by Esc key. I will try to add this for the next release.

**Comment by hyuri** [comment]
Nice!

**Comment by iman-salmani** [comment]
Fixed 7bef5ab0cc6f236dfa69434641700187fe0665ef
