### ISSUE TITLE
[Bug] Straight corners on bottom of bottom tasks

### ISSUE THREAD

**Issue by hyuri** [iman-salmani/iplan#31]
Notice how the highlight on the bottom of the bottom task is square on the corners.

![image](https://github.com/iman-salmani/iplan/assets/18584014/21f5144c-ab0c-4b5b-a8b0-f7fac79761c9)

There's something weird going on at the edges:

![image](https://github.com/iman-salmani/iplan/assets/18584014/da6b961e-dfe5-4af7-9080-6e620672405c)

**Comment by iman-salmani** [comment]
because it has a hidden placeholder.
this one will be fixed while redesigning tasks and their drag and drop.

**Comment by hyuri** [comment]
Nice!
