### ISSUE TITLE
[Feature Request] Add option to place new tasks at the bottom of the list

### ISSUE THREAD

**Issue by hyuri** [iman-salmani/iplan#34]
It would be nice if there was an option (perhaps in a new [global] Preferences dialog?) to choose whether new tasks should be added to the top of the list, or to the bottom.

Often when adding tasks to a list, I think about it in an ascending order, so I start by adding "Task 1", then "Task 2", "Task 3", etc. and, right now, they end up like this:
Task 3
Task 2
Task 1

By choosing to have new tasks added to the bottom of the list, they would end up like this:
Task 1
Task 2
Task 3

**Comment by iman-salmani** [comment]
Me too! especially while adding subtasks.
but what about lists with many tasks every time a new task is added window should scroll to that!
The solution can be to add a new button at the bottom of the list for this purpose.

**Comment by hyuri** [comment]
Good idea!
