### ISSUE TITLE
[Feature Request] Change the name to iPlan

### ISSUE THREAD

**Issue by AchillesBoi** [iman-salmani/iplan#36]
IPlan, with a capital 'I', looks odd. The name looks a million times better as iPlan.

That is all.

**Comment by iman-salmani** [comment]
Hi. Thanks for mentioning this.
I used the capital form I to bold the user part. But I should take more time to think about this.
any suggestion is appreciated.

**Comment by AchillesBoi** [comment]
The lowercase 'i' looks more visually appealing than capital 'I'. Additionally, it helps differenciate the capital 'I' from a lowercase 'l'. If you can't differenciate between the two in the previous sentence then you can see that there is a problem.

iPlan > IPlan

**Comment by iman-salmani** [comment]
the discussion will be continued on this issue #3.
