### ISSUE TITLE
[Feature Request] Disallow empty project names

### ISSUE THREAD

**Issue by dominikheinz** [iman-salmani/iplan#37]
Just an idea, maybe it would make sense to expect from the user to specify a name for a project.
Right now, empty names are allowed which can lead to some weird looking empty list icons. For example, I pressed the + button by accident and the next day when I reopened the app I was confused why there was an empty item in the list.

[Screencast from 2023-06-20 23-24-47.webm](https://github.com/iman-salmani/iplan/assets/32770080/d9b18f06-68d0-4932-b6cc-a6eb3c1c8c9d)

Unsure if that is intentional, or not ^^

**Comment by iman-salmani** [comment]
I agree. should be a window for creating a project to the user can change other options or cancel.
