### ISSUE TITLE
using the close button from the app title bar doesn't close the app

### ISSUE THREAD

**Issue by soumyaDghosh** [iman-salmani/iplan#41]
If I close the app from the close button of the app's title bar, it keeps the app open in background. This issue is same in both flatpak and snap(that I have created for your app and serving well in the snap store).

**Comment by iman-salmani** [comment]
Ah. Thank you.

IPlan need to keep running for sending reminders. you can quit the application by `ctrl + q` shortcut or the quit button in the primary menu.
It seems the app does not follow the `Run in Background` option in gnome settings.
For the next version, an option to disable this will be added.

about snap, do you like to send me a connection way?
mail: contact.imansalmani@gmail.com
if you prefer Matrix this is my account:  @imansalmani:matrix.org
