### ISSUE TITLE
Upgraded IPlan from version 1.6.0 to 1.7.0; App is not starting

### ISSUE THREAD

**Issue by umamaheswaran-j** [iman-salmani/iplan#45]
Issue observed from:
OS: Ubuntu 23.04
Flatpak version: 1.14.4

I  upgraded IPlan from 1.6.0 to 1.7.0  with `flatpak update` command.  

When IPlan Favorites shortcut was clicked, IPlan was not started.  With the command:
`flatpak run ir.imansalmani.IPlan`

following message is shown:
```
thread 'main' panicked at 'Failed to migrate database: QueryReturnedNoRows', src/db/manager.rs:94:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Kindly requesting to resolve. 

Great App. I would like to use the app continuously.

Thank you very much.

**Comment by iman-salmani** [comment]
Hi. Thank you for reporting this.
Have you used the app before version 1.6.0?
> Before June 23

**Comment by azuredusk10** [comment]
Hi, I'm also experiencing this problem after upgrading to 1.7.0 from 1.6.0 today. I'm using Fedora 38.

Let me know if there's anything I can send to help debug the problem. Thanks for developing such a fantastic app!

**Comment by iman-salmani** [comment]
Hi @azuredusk10.
Have you used the app before version 1.6.0?
> Before June 23

**Comment by iman-salmani** [comment]
If so, it may happen because you removed some tasks, but the subtasks hid in the database. And database migration failed to gather deleted task information.

**Comment by iman-salmani** [comment]
I will try to publish a new version today to fix this issue.
until that, you can downgrade the app version.
```bash
sudo flatpak update --commit=496899406ebf90c794c518f0e9bc3c9d6152576870adae5216f0be9a10d367f7 ir.imansalmani.IPlan
```

**Comment by umamaheswaran-j** [comment]
> 
Hi @iman-salmani. 
I have been using IPlan from version 1.6.0 only.  Thank you.

**Comment by azuredusk10** [comment]
> Hi @azuredusk10. Have you used the app before version 1.6.0?
> 
> > Before June 23

Hi @iman-salmani , yes I've been using it since about version 1.4.0. Downgrading from 1.7.0 to 1.6.0 has solved the issue for now :+1:
