### ISSUE TITLE
The day of the week for the task deadline can be misleading

### ISSUE THREAD

**Issue by SokolovskyMaxim** [iman-salmani/iplan#47]
when tasks are assigned deadline dates on different dates with the same day of the week, one day of the week is displayed, this may confuse the user

![Новый Документ - Selection](https://github.com/iman-salmani/iplan/assets/106545001/eb8b0077-f580-47d9-9372-94f21185b5f9)

**Comment by iman-salmani** [comment]
Thanks for mentioning this
