### ISSUE TITLE
[Bug] Unable to name subtasks

### ISSUE THREAD

**Issue by hyuri** [iman-salmani/iplan#51]
Hi!

When I add a new subtask, the name I choose is not saved. And when I rename an existing subtask, the new name is not saved either, it gets reverted to the previous name.

https://github.com/iman-salmani/iplan/assets/18584014/0b2fec7f-2ebe-4ef7-bef3-54a67a9109cd

Version: 1.9
Format: Flatpak

I've reverted back to the previous version (1.8.1) for now.

**Comment by iman-salmani** [comment]
Hi @hyuri . Thank you for reporting this.
It also can happen while renaming tasks.
I will try to Release 1.9.1 this week.
Just in case someone else sees this, there is 2 way to work around it:
* Set date after renaming task
* Back to the previous version
```bash
sudo flatpak update --commit=99bd4408cdbd65c95d18029e050802f4e769a5572d5b78f3eaaa6692d2fba53f ir.imansalmani.IPlan
```

**Comment by hyuri** [comment]
Thank you for fixing it!
