### ISSUE TITLE
Adding tasks to taks fails

### ISSUE THREAD

**Issue by lapor-kris** [iman-salmani/iplan#54]
When I add additional task (subtask, which is part of a task) to specific task it fails to show the written task. It just shows empty tasks.

I have the latest 1.9.1 from Flathub.

Thanks

edit: If I restart the app, it works as expected. I use Fedora 38, if that helps

**Comment by iman-salmani** [comment]
I Can’t Replicate the Problem can you show this in a screenshot or screencast?

**Comment by lapor-kris** [comment]
I will when it happens again. It's not that often and I think it happens when I have it open for a longer period of time.

**Comment by lapor-kris** [comment]
I cannot replicate it. But I suspect it was something wrong with my system. I think you can close this bug for now.
