### ISSUE TITLE
[Bug] Subtasks order not matching between project and task view

### ISSUE THREAD

**Issue by hyuri** [iman-salmani/iplan#59]
Hi!

If I create a few subtasks in task view and then drag & drop to re-order them — up or down...
![image](https://github.com/iman-salmani/iplan/assets/18584014/b54cb1e5-4214-4a2e-90c4-306da6a79c86)

...they don't display the correct order in project view:
![image](https://github.com/iman-salmani/iplan/assets/18584014/98d18037-b357-47ef-be3e-5ab115843798)

**Comment by iman-salmani** [comment]
Thank you for reporting this.
Do you have this issue even after the reopening window?

**Comment by hyuri** [comment]
No, reopening the app updates the order in project view.

**Comment by hyuri** [comment]
It's been happening again. Doesn't update the list until I close the app and open again.
